### ISSUE TITLE
[UI-17] Highlight Text Component

### ISSUE THREAD

**Issue by fpunny** [hack-the-6ix/landing-2022#12]
### Requirements
 - Behaves similar to how a `<strong>` or `<em>` element works
 - The color of highlight should be customizable
 - Should support text-wrapping

### Resources
 - https://css-tricks.com/styling-underlines-web/ (Some inspiration on possible implementations)

### Mockup Reference
![Screen Shot 2022-04-25 at 12 52 28 AM](https://user-images.githubusercontent.com/23289083/165023027-d98069a9-630a-4423-9fd1-ce594a12e2ca.png)

**Comment by RuyiLi** [comment]
Is the highlight supposed to have a fixed height? It goes under the text in the above image, but here it's contained within the text (i.e. ends just above the bottom of the "p" in "open").
![image](https://user-images.githubusercontent.com/16544254/166870283-2dabd3fb-8fc3-413a-b292-ac29a28ed128.png)
Can't seem to find anything in the Figma regarding this

**Comment by fpunny** [comment]
Hmm we can try making it relative to the parent via `em` for the height and offset. If that doesn't work, then we can make it "dynamic" with props to css variables

**Comment by RuyiLi** [comment]
Right now I have it so it spans the bottom half of the line (-0.5em, with box shadow).

↓↓ what I have currently
![image](https://user-images.githubusercontent.com/16544254/167057569-e9955d61-aa09-48e1-bdfd-b0639e0195f4.png)

If we want the behavior in the first image I need to add an additional outset shadow, and if we want the behavior in the second I need to add an additional inset shadow. I can add a prop for this, but I'm not sure what the size of the gaps (shown with the red lines below) should be.

↓↓ from Figma
![image](https://user-images.githubusercontent.com/16544254/167057707-376924a0-73af-4123-9e4a-b217bcadaa09.png)

**Comment by fpunny** [comment]
ngl i think this would be good enough :3 If design complains about it, then we can look into this further. I dont want to waste too much of our time on this
